### ISSUE TITLE
Port slufl to Ansible 2.4

### ISSUE THREAD

**Issue by tsubic** [damienfrancois/slufl2#13]
Hi,

I tried to run slufl but have encountered difficulties in running it with the latest Ansible 2.4.
I'm not sure for which exact Ansible version slufl was built, but in the most recent version, Ansible 2.4, a lot of things changed in the sytax of ansible python modules, mainly the Inventory, Variable and CLI submodules.
Here is the changelog and a link to a porting guide:

[Ansible 2.4 changelog](https://github.com/ansible/ansible/blob/stable-2.4/CHANGELOG.md#2.4)
[Ansible 2.4 porting guide](https://docs.ansible.com/ansible/2.4/porting_guide_2.4.html)

Keep in mind that the porting guide is meant for porting from 2.3 to 2.4, so there is most likely more work to be done.

**Comment by damienfrancois** [comment]
This version is running fine in our staging environment that runs Ansible v2.3 and I confirm it is broken with Ansible v2.4

I will try and fix that.

**Comment by damienfrancois** [comment]
A version working with Ansible v2.4 is available in branch https://github.com/damienfrancois/slufl2/tree/ansiblev2.4
