### ISSUE TITLE
ansiblev2.4 branch doesn't work in Ansible 2.9

### ISSUE THREAD

**Issue by AndresTanasijczuk** [damienfrancois/slufl2#16]
At CP3 we upgraded Ansible in the machine running slufll2 to version 2.9.10. The Ansible python API, being for internal use only, has changed in a non-backward compatible way. I have created a ansiblev2.9 branch in my fork of this project with the needed modifications to make slufl2 work with Ansible 2.9: https://github.com/AndresTanasijczuk/slufl2/tree/ansiblev2.9
I think the modifications are needed for Ansible 2.7 already. 

I wanted to create a pull request, but since I think that the idea would be to create a new branch, I can not make the pull request to a new branch. I am running the slufld script from my new branch at CP3 and I can confirm that it works.

**Comment by damienfrancois** [comment]
Thanks Andres. I created a Ansiblev2.9 branch: https://github.com/damienfrancois/slufl2/tree/ansiblev2.9 Can you please issue a Pull Request against it?
